const ERROR_CODES = Object.freeze({
    SYSTEM: Object.freeze({
        INTERNAL_SERVER_ERROR:
            "INTERNAL_SERVER_ERROR"
    }),

    VALIDATION: Object.freeze({
        INVALID_INPUT: "INVALID_INPUT",
        VALIDATION_FAILED:
            "VALIDATION_FAILED"
    }),

    CONVERSATION: {
  SELF_CONVERSATION_NOT_ALLOWED:
    "SELF_CONVERSATION_NOT_ALLOWED",

  PARTICIPANT_UNAVAILABLE:
    "CONVERSATION_PARTICIPANT_UNAVAILABLE",

  CONVERSATION_NOT_FOUND:
    "CONVERSATION_NOT_FOUND",

  NOT_A_MEMBER:
    "CONVERSATION_NOT_A_MEMBER",
    INVALID_GROUP_MEMBERS:
  "INVALID_GROUP_MEMBERS",

GROUP_MEMBER_LIMIT_EXCEEDED:
  "GROUP_MEMBER_LIMIT_EXCEEDED",
  GROUP_ACTION_NOT_ALLOWED:
  "GROUP_ACTION_NOT_ALLOWED",

INSUFFICIENT_GROUP_PERMISSION:
  "INSUFFICIENT_GROUP_PERMISSION",

GROUP_MEMBER_NOT_FOUND:
  "GROUP_MEMBER_NOT_FOUND",

OWNER_TRANSFER_REQUIRED:
  "OWNER_TRANSFER_REQUIRED",

INVALID_OWNERSHIP_TRANSFER:
  "INVALID_OWNERSHIP_TRANSFER",
},

MESSAGE: {
  MESSAGE_NOT_FOUND:
    "MESSAGE_NOT_FOUND",

  IDEMPOTENCY_CONFLICT:
    "MESSAGE_IDEMPOTENCY_CONFLICT",

  MESSAGE_UNAVAILABLE:
    "MESSAGE_UNAVAILABLE",
},

    AUTH: Object.freeze({
        AUTHENTICATION_REQUIRED:
            "AUTHENTICATION_REQUIRED",
        INVALID_CREDENTIALS:
            "INVALID_CREDENTIALS",
        FORBIDDEN: "FORBIDDEN",
        ACCOUNT_SUSPENDED:
            "ACCOUNT_SUSPENDED",
        ACCOUNT_DEACTIVATED:
            "ACCOUNT_DEACTIVATED",
        ACCOUNT_NOT_VERIFIED: "ACCOUNT_NOT_VERIFIED",
        INVALID_REFRESH_TOKEN:
  "INVALID_REFRESH_TOKEN",

SESSION_EXPIRED:
  "SESSION_EXPIRED",

SESSION_REVOKED:
  "SESSION_REVOKED",

REFRESH_TOKEN_REUSE_DETECTED:
  "REFRESH_TOKEN_REUSE_DETECTED",

REFRESH_ALREADY_ROTATED:
  "REFRESH_ALREADY_ROTATED",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
    }),

    USER: Object.freeze({
        USERNAME_ALREADY_EXISTS:
            "USERNAME_ALREADY_EXISTS",
        EMAIL_ALREADY_EXISTS:
            "EMAIL_ALREADY_EXISTS",
        PHONE_ALREADY_EXISTS:
            "PHONE_ALREADY_EXISTS",
        USER_NOT_FOUND:
            "USER_NOT_FOUND"
    }),

    VERIFICATION: Object.freeze({
        INVALID_CODE:
            "INVALID_VERIFICATION_CODE",
        CODE_EXPIRED:
            "VERIFICATION_CODE_EXPIRED",
        CODE_ALREADY_USED:
            "VERIFICATION_CODE_ALREADY_USED",
        TOO_MANY_ATTEMPTS:
            "VERIFICATION_TOO_MANY_ATTEMPTS",
        CHALLENGE_NOT_FOUND:
            "VERIFICATION_CHALLENGE_NOT_FOUND",
            RESEND_TOO_SOON:
    "VERIFICATION_RESEND_TOO_SOON",
    })
});


module.exports = ERROR_CODES;